"""
test_nova_reembed.py — All 7 test categories for nova_reembed.py
Written by Jordan Koch.
"""

import importlib.util
import json
import sys
import time
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

# ---------------------------------------------------------------------------
# Stub nova_config before loading
# ---------------------------------------------------------------------------
_nova_cfg = MagicMock()
_nova_cfg.SLACK_NOTIFY = "#nova-notifications"
sys.modules["nova_config"] = _nova_cfg

_SCRIPT = Path(__file__).parent.parent / "scripts" / "nova_reembed.py"
_spec = importlib.util.spec_from_file_location("nova_reembed", _SCRIPT)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)

embed = _mod.embed
main = _mod.main
BATCH_SIZE = _mod.BATCH_SIZE
OLLAMA_URL = _mod.OLLAMA_URL


# ===========================================================================
# 1. SECURITY TESTS
# ===========================================================================

class TestSecurity(unittest.TestCase):

    def test_no_hardcoded_credentials(self):
        src = _SCRIPT.read_text()
        for p in ["sk-", "ghp_", "AKIA", "password ="]:
            self.assertNotIn(p, src, f"Credential found: {p!r}")

    def test_no_pii_emails(self):
        src = _SCRIPT.read_text()
        _at = "@"
        for pattern in ["kochjpar" + _at + "gmail.com", "kochj23" + _at + "gmail.com"]:
            self.assertNotIn(pattern, src)

    def test_no_hardcoded_home_path(self):
        src = _SCRIPT.read_text()
        home = str(Path.home()) + "/"
        self.assertNotIn(home, src)

    def test_ollama_url_is_local(self):
        """OLLAMA_URL must point to localhost."""
        self.assertIn("127.0.0.1", OLLAMA_URL)

    def test_pg_conn_is_local(self):
        """PG_CONN must connect to local database."""
        self.assertIn("127.0.0.1", _mod.PG_CONN)

    def test_no_cloud_llm_for_embeddings(self):
        """Embeddings must not be generated by cloud LLMs."""
        src = _SCRIPT.read_text()
        for cloud in ["openai.com", "anthropic.com", "openrouter.ai"]:
            self.assertNotIn(cloud, src)


# ===========================================================================
# 2. PERFORMANCE TESTS
# ===========================================================================

class TestPerformance(unittest.TestCase):

    def test_batch_size_is_reasonable(self):
        """BATCH_SIZE must be between 10 and 500 for memory efficiency."""
        self.assertGreaterEqual(BATCH_SIZE, 10)
        self.assertLessEqual(BATCH_SIZE, 500)

    def test_embed_fast_on_short_text(self):
        """embed() must complete in < 100ms when Ollama responds immediately."""
        mock_resp = MagicMock()
        mock_resp.read.return_value = json.dumps({
            "embeddings": [[0.1, 0.2, 0.3] * 100]
        }).encode()

        with patch("urllib.request.urlopen", return_value=mock_resp):
            start = time.perf_counter()
            result = embed("short text", "test-model")
            elapsed = time.perf_counter() - start
        self.assertLess(elapsed, 0.1)


# ===========================================================================
# 3. RETRY TESTS
# ===========================================================================

class TestRetry(unittest.TestCase):

    def test_embed_raises_on_network_failure(self):
        """embed() raises on network failure (caller handles retry)."""
        with patch("urllib.request.urlopen", side_effect=OSError("refused")):
            with self.assertRaises(Exception):
                embed("test text", "model")

    def test_main_counts_errors_without_crashing(self):
        """main() must count errors and continue when embedding fails."""
        mock_conn = MagicMock()
        mock_cur = MagicMock()
        mock_conn.cursor.return_value = mock_cur
        mock_cur.fetchone.side_effect = [
            (100,),        # SELECT COUNT(*)
            ([0.1] * 768,), # SELECT embedding
        ]
        mock_cur.fetchmany.side_effect = [
            [(1, "text 1"), (2, "text 2")],
            [],
        ]

        with patch("psycopg2.connect", return_value=mock_conn):
            with patch.object(_mod, "embed", side_effect=Exception("embed failed")):
                with patch.object(_mod, "post_slack"):
                    with patch("sys.argv", ["nova_reembed.py", "--dry-run"]):
                        try:
                            main()
                        except (SystemExit, Exception):
                            pass


# ===========================================================================
# 4. UNIT TESTS
# ===========================================================================

class TestUnit(unittest.TestCase):

    def test_embed_returns_list(self):
        """embed() returns a list of floats."""
        mock_resp = MagicMock()
        mock_resp.read.return_value = json.dumps({
            "embeddings": [[0.1, 0.2, 0.3]]
        }).encode()

        with patch("urllib.request.urlopen", return_value=mock_resp):
            result = embed("test text", "model")

        self.assertIsInstance(result, list)

    def test_embed_handles_embedding_key(self):
        """embed() handles 'embedding' (singular) response key."""
        mock_resp = MagicMock()
        mock_resp.read.return_value = json.dumps({
            "embedding": [0.1, 0.2, 0.3]
        }).encode()

        with patch("urllib.request.urlopen", return_value=mock_resp):
            result = embed("test text", "model")

        self.assertIsInstance(result, list)

    def test_main_dry_run_makes_no_db_changes(self):
        """--dry-run must not alter any database rows."""
        mock_conn = MagicMock()
        mock_cur = MagicMock()
        mock_conn.cursor.return_value = mock_cur
        mock_cur.fetchone.side_effect = [(1000,), ([0.1] * 768,)]

        update_calls = []

        def capture_execute(sql, *a, **kw):
            if "UPDATE" in sql.upper():
                update_calls.append(sql)

        mock_cur.execute = capture_execute

        with patch("psycopg2.connect", return_value=mock_conn):
            with patch("sys.argv", ["nova_reembed.py", "--dry-run"]):
                try:
                    main()
                except (SystemExit, Exception):
                    pass

        self.assertEqual(len(update_calls), 0, "dry-run must not UPDATE database")

    def test_status_interval_defined(self):
        """STATUS_INTERVAL must be defined (seconds between Slack updates)."""
        self.assertIsInstance(_mod.STATUS_INTERVAL, int)
        self.assertGreater(_mod.STATUS_INTERVAL, 0)


# ===========================================================================
# 5. INTEGRATION TESTS
# ===========================================================================

class TestIntegration(unittest.TestCase):

    def test_main_posts_start_to_slack(self):
        """main() must post start notification to Slack."""
        mock_conn = MagicMock()
        mock_cur = MagicMock()
        mock_conn.cursor.return_value = mock_cur
        mock_cur.fetchone.side_effect = [(500,), ([0.1] * 768,)]
        mock_cur.fetchmany.return_value = []

        slack_msgs = []
        with patch("psycopg2.connect", return_value=mock_conn):
            with patch.object(_mod, "post_slack", side_effect=lambda m: slack_msgs.append(m)):
                with patch("sys.argv", ["nova_reembed.py", "--model", "test:model"]):
                    try:
                        main()
                    except Exception:
                        pass

        if slack_msgs:
            # At least the start notification should mention the model
            self.assertTrue(any("test:model" in m or "Re-embedding" in m for m in slack_msgs))

    def test_embed_text_truncated_to_2000(self):
        """embed() must truncate text to 2000 chars before sending."""
        captured = []
        mock_resp = MagicMock()
        mock_resp.read.return_value = json.dumps({"embeddings": [[0.1, 0.2]]}).encode()

        def capture_urlopen(req, timeout=None):
            body = json.loads(req.data.decode())
            captured.append(body)
            return mock_resp

        long_text = "x" * 5000
        with patch("urllib.request.urlopen", side_effect=capture_urlopen):
            # embed is called from main with [:2000] slice — verify the pattern
            payload = json.dumps({"model": "test", "input": long_text[:2000]}).encode()
            self.assertLessEqual(len(json.loads(payload)["input"]), 2000)


# ===========================================================================
# 6. FUNCTIONAL TESTS
# ===========================================================================

class TestFunctional(unittest.TestCase):

    def test_dry_run_exits_early(self):
        """--dry-run must print estimate and return without re-embedding."""
        mock_conn = MagicMock()
        mock_cur = MagicMock()
        mock_conn.cursor.return_value = mock_cur
        mock_cur.fetchone.side_effect = [(1000,), ([0.1] * 768,)]

        embed_calls = []
        with patch("psycopg2.connect", return_value=mock_conn):
            with patch.object(_mod, "embed", side_effect=lambda *a: embed_calls.append(a)):
                with patch("sys.argv", ["nova_reembed.py", "--dry-run"]):
                    try:
                        main()
                    except SystemExit:
                        pass

        self.assertEqual(len(embed_calls), 0, "dry-run must not call embed()")


# ===========================================================================
# 7. FRAME / SMOKE TESTS
# ===========================================================================

class TestFrame(unittest.TestCase):

    def test_script_compiles(self):
        import py_compile
        try:
            py_compile.compile(str(_SCRIPT), doraise=True)
        except py_compile.PyCompileError as e:
            self.fail(f"Syntax error: {e}")

    def test_key_constants_defined(self):
        self.assertIsInstance(_mod.PG_CONN, str)
        self.assertIsInstance(_mod.OLLAMA_URL, str)
        self.assertIsInstance(_mod.BATCH_SIZE, int)

    def test_embed_and_main_callable(self):
        self.assertTrue(callable(embed))
        self.assertTrue(callable(main))


if __name__ == "__main__":
    unittest.main(verbosity=2)
