#!/usr/bin/env python3
"""Ingest 1000 facts about liver failure, cirrhosis, paracentesis, and orthostatic hypotension into Nova's memory."""
import json, sys, time, urllib.request
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path.home() / ".openclaw/scripts"))
import nova_config

MEMORY_URL = "http://192.168.1.6:18790/remember"
count = 0
failed = 0
start_time = time.time()

def log(msg):
    print(f"[liver-disease {datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)

def slack_post(text):
    nova_config.post_both(text, slack_channel=nova_config.SLACK_NOTIFY)

def remember(text):
    global count, failed
    payload = json.dumps({"text": text, "source": "local_knowledge", "metadata": {"type": "medical_liver_disease", "topics": ["liver_failure", "cirrhosis", "paracentesis", "orthostatic_hypotension"]}}).encode()
    req = urllib.request.Request(MEMORY_URL, data=payload, headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=10):
            count += 1
            return True
    except Exception as e:
        failed += 1
        if failed <= 5:
            log(f"  Failed: {e}")
        return False

# ═══════════════════════════════════════════════════════════════════════════════
# CIRRHOSIS — Pathophysiology & General (Facts 1-250)
# ═══════════════════════════════════════════════════════════════════════════════
CIRRHOSIS_GENERAL = [
    "Cirrhosis is the end-stage of chronic liver disease characterized by diffuse fibrosis, regenerative nodules, and architectural distortion of the liver.",
    "The word 'cirrhosis' derives from the Greek 'kirrhos' meaning tawny/yellowish-brown, referring to the color of the diseased liver surface.",
    "Cirrhosis represents irreversible scarring of the liver, though early-stage compensated cirrhosis can remain stable for years with proper management.",
    "The liver has remarkable regenerative capacity — up to 75% can be removed and it will regenerate, but cirrhosis disrupts this ability through fibrotic replacement.",
    "Alcohol-related liver disease accounts for approximately 50% of cirrhosis cases in Western countries.",
    "Non-alcoholic fatty liver disease (NAFLD) is the fastest-growing cause of cirrhosis worldwide, closely linked to obesity and metabolic syndrome.",
    "Hepatitis C was historically the second most common cause of cirrhosis but is now curable with direct-acting antivirals (DAAs) achieving >95% sustained virologic response.",
    "Hepatitis B remains a leading cause of cirrhosis globally, particularly in Asia and sub-Saharan Africa where vertical transmission is common.",
    "Cirrhosis develops over years to decades — alcohol-related cirrhosis typically takes 10-20 years of heavy drinking to develop.",
    "The METAVIR scoring system grades liver fibrosis from F0 (no fibrosis) to F4 (cirrhosis), with F3 being bridging fibrosis.",
    "Hepatic stellate cells are the primary cells responsible for liver fibrosis — when activated by injury, they transform into myofibroblasts that produce excess collagen.",
    "Cirrhosis disrupts the normal hepatic architecture, compressing sinusoids and increasing intrahepatic vascular resistance, leading to portal hypertension.",
    "Portal hypertension is defined as a hepatic venous pressure gradient (HVPG) exceeding 5 mmHg; clinically significant portal hypertension occurs above 10 mmHg.",
    "Compensated cirrhosis means the liver is damaged but still functioning adequately — patients may be asymptomatic for years.",
    "Decompensated cirrhosis occurs when complications develop: ascites, variceal hemorrhage, hepatic encephalopathy, or jaundice.",
    "The transition from compensated to decompensated cirrhosis occurs at a rate of approximately 5-7% per year.",
    "Once decompensation occurs, median survival drops from >12 years (compensated) to approximately 2 years without liver transplantation.",
    "The Child-Pugh score classifies cirrhosis severity using bilirubin, albumin, INR, ascites, and encephalopathy — Class A (5-6), B (7-9), C (10-15).",
    "Child-Pugh Class A has a 1-year survival of approximately 100%, Class B approximately 80%, and Class C approximately 45%.",
    "The Model for End-Stage Liver Disease (MELD) score uses bilirubin, creatinine, and INR to predict 3-month mortality and prioritize organ allocation for transplant.",
    "MELD scores range from 6 to 40; a score above 30 indicates very severe disease with >50% 3-month mortality without transplant.",
    "MELD-Na incorporates serum sodium, improving mortality prediction since hyponatremia is a strong predictor of poor outcomes in cirrhosis.",
    "Liver biopsy was historically the gold standard for diagnosing cirrhosis but is increasingly replaced by non-invasive methods like transient elastography (FibroScan).",
    "FibroScan measures liver stiffness in kilopascals (kPa) — values above 12-14 kPa are strongly suggestive of cirrhosis depending on etiology.",
    "The FIB-4 index is a simple blood test calculation using age, AST, ALT, and platelet count to estimate liver fibrosis stage non-invasively.",
    "Thrombocytopenia (low platelets) is often the first laboratory sign of cirrhosis, resulting from splenic sequestration due to portal hypertension and reduced thrombopoietin production.",
    "Cirrhosis causes decreased synthesis of most clotting factors (produced by the liver), leading to coagulopathy reflected by elevated PT/INR.",
    "Despite elevated INR, patients with cirrhosis are not necessarily 'auto-anticoagulated' — they also have decreased anticoagulant proteins (protein C, S, antithrombin), creating a rebalanced hemostasis.",
    "Hypoalbuminemia is a hallmark of cirrhosis — albumin is synthesized exclusively by the liver and has a half-life of approximately 20 days.",
    "Serum albumin below 3.5 g/dL indicates synthetic dysfunction; below 2.5 g/dL is associated with significantly increased morbidity and mortality.",
    "Spider angiomata (spider nevi) are found in up to 33% of cirrhosis patients — small arterial vessels with radiating branches that blanch with central pressure.",
    "Palmar erythema occurs in up to 23% of cirrhosis patients due to elevated estrogen levels from impaired hepatic metabolism.",
    "Gynecomastia in male cirrhosis patients results from increased peripheral conversion of androgens to estrogens and decreased hepatic clearance of estrogens.",
    "Caput medusae — dilated periumbilical veins visible on the abdomen — is a sign of portal hypertension with portosystemic collateral circulation.",
    "Dupuytren's contracture is associated with alcoholic cirrhosis but is not specific — it occurs in up to 33% of patients with alcohol-related liver disease.",
    "Jaundice becomes clinically apparent when serum bilirubin exceeds approximately 2.5-3.0 mg/dL — first visible in the sclera, then skin.",
    "Fetor hepaticus is a musty, sweet breath odor in advanced liver disease caused by dimethyl sulfide and other volatile sulfur compounds not cleared by the failing liver.",
    "Asterixis (liver flap) is an involuntary flapping tremor of the hands when wrists are dorsiflexed — a classic sign of hepatic encephalopathy.",
    "Muscle wasting (sarcopenia) affects 40-70% of cirrhosis patients and is an independent predictor of mortality, complications, and poor transplant outcomes.",
    "Sarcopenia in cirrhosis results from hyperammonemia, impaired protein synthesis, increased autophagy, and hormonal imbalances.",
    "Cirrhotic cardiomyopathy is a form of cardiac dysfunction characterized by impaired contractile response to stress, diastolic dysfunction, and electrophysiological abnormalities.",
    "Hepatorenal syndrome (HRS) occurs in advanced cirrhosis — intense renal vasoconstriction due to splanchnic vasodilation and reduced effective circulating volume.",
    "HRS Type 1 (now HRS-AKI) is rapidly progressive with doubling of creatinine to >2.5 mg/dL within 2 weeks, carrying >80% mortality without treatment.",
    "HRS Type 2 (now HRS-CKD) is more gradual, typically presenting with refractory ascites and moderate renal impairment.",
    "Terlipressin combined with albumin is the first-line treatment for HRS in many countries — it's a vasopressin analog that constricts splanchnic vessels.",
    "Spontaneous bacterial peritonitis (SBP) occurs in 10-30% of hospitalized cirrhosis patients with ascites — infection of ascitic fluid without a surgically treatable source.",
    "SBP is diagnosed by ascitic fluid neutrophil count ≥250 cells/mm³ — empiric antibiotics (usually ceftriaxone) should begin immediately without waiting for cultures.",
    "SBP prophylaxis with norfloxacin or trimethoprim-sulfamethoxazole is indicated in patients with ascitic fluid protein <1.5 g/dL or prior SBP episode.",
    "Hepatic encephalopathy affects up to 80% of patients with cirrhosis to some degree — ranging from minimal/covert to overt coma.",
    "Ammonia is central to hepatic encephalopathy pathogenesis — produced by gut bacteria and normally cleared by the liver's urea cycle.",
    "Lactulose is first-line treatment for hepatic encephalopathy — it's a non-absorbable disaccharide that acidifies colonic pH, converting ammonia to non-absorbable ammonium.",
    "Rifaximin (a non-absorbable antibiotic) added to lactulose reduces hepatic encephalopathy recurrence by approximately 50% compared to lactulose alone.",
    "The West Haven criteria grade hepatic encephalopathy: Grade 1 (mild confusion), Grade 2 (drowsiness/disorientation), Grade 3 (somnolence/semi-stupor), Grade 4 (coma).",
    "Minimal hepatic encephalopathy has no overt clinical signs but can be detected by psychometric tests — it impairs driving ability and quality of life.",
    "Protein restriction is no longer recommended for hepatic encephalopathy — adequate protein intake (1.2-1.5 g/kg/day) is important to prevent sarcopenia.",
    "Branched-chain amino acids (leucine, isoleucine, valine) supplementation may improve hepatic encephalopathy and muscle mass in cirrhosis patients.",
    "Hepatocellular carcinoma (HCC) develops in cirrhosis at a rate of 1-8% per year depending on etiology — surveillance with ultrasound every 6 months is recommended.",
    "Alpha-fetoprotein (AFP) alone is insufficient for HCC screening — it has sensitivity of only 60% and specificity of about 80% at the 20 ng/mL cutoff.",
    "The Barcelona Clinic Liver Cancer (BCLC) staging system guides HCC treatment from very early (0) through early (A), intermediate (B), advanced (C), to terminal (D).",
    "Liver transplantation for HCC within Milan criteria (single tumor ≤5cm or up to 3 tumors each ≤3cm) achieves 5-year survival rates of 70-80%.",
    "Autoimmune hepatitis causes cirrhosis in approximately 40% of untreated cases and responds to immunosuppression with prednisone and azathioprine.",
    "Primary biliary cholangitis (PBC, formerly primary biliary cirrhosis) is an autoimmune disease targeting intrahepatic bile ducts — positive anti-mitochondrial antibodies (AMA) in >90% of cases.",
    "Primary sclerosing cholangitis (PSC) causes progressive fibrosis of intra- and extrahepatic bile ducts — strongly associated with inflammatory bowel disease (70-80% have ulcerative colitis).",
    "Wilson disease (hepatolenticular degeneration) causes cirrhosis through copper accumulation — diagnosed by low ceruloplasmin, elevated 24-hour urine copper, and Kayser-Fleischer rings.",
    "Hereditary hemochromatosis causes cirrhosis through iron overload — most commonly due to C282Y homozygosity in the HFE gene in Northern European populations.",
    "Alpha-1 antitrypsin deficiency can cause cirrhosis (and emphysema) — the PiZZ phenotype carries the highest risk of liver disease, affecting 1 in 3,000 people of European descent.",
    "Budd-Chiari syndrome (hepatic vein thrombosis) causes congestive hepatopathy and cirrhosis — often associated with myeloproliferative disorders or thrombophilias.",
    "Cardiac cirrhosis results from chronic right-sided heart failure causing hepatic congestion — the liver becomes 'nutmeg' in appearance from centrilobular necrosis.",
    "Non-alcoholic steatohepatitis (NASH) progresses to cirrhosis in approximately 10-20% of cases over 10-20 years.",
    "The NAFLD fibrosis score uses age, BMI, diabetes status, AST/ALT ratio, platelet count, and albumin to identify patients at risk for advanced fibrosis.",
    "Cryptogenic cirrhosis (unknown cause) accounts for 5-10% of cases — many are likely 'burned out' NASH where steatosis has resolved as cirrhosis progresses.",
    "Liver stiffness measurement by FibroScan can be falsely elevated by hepatic inflammation (flares), congestion, cholestasis, or recent food intake.",
    "Cirrhosis affects drug metabolism profoundly — both phase I (CYP450 oxidation) and phase II (conjugation) reactions are impaired, requiring dose adjustments for many medications.",
    "NSAIDs should be avoided in cirrhosis due to risks of renal impairment, GI bleeding, and impaired platelet function — acetaminophen (≤2g/day) is preferred for pain.",
    "Aminoglycosides are nephrotoxic and should be avoided in cirrhosis; fluoroquinolones carry risk of tendon rupture especially with concurrent corticosteroids.",
    "Statins are safe in compensated cirrhosis and may have antifibrotic properties — they should be discontinued in decompensated disease.",
    "Beta-blockers (particularly non-selective: propranolol, nadolol, carvedilol) reduce portal pressure and prevent variceal bleeding in cirrhosis.",
    "Carvedilol may be more effective than propranolol for portal hypertension because it also reduces intrahepatic resistance through alpha-1 blockade.",
    "Beta-blockers should be discontinued in decompensated cirrhosis with refractory ascites, SBP, or severe hypotension — the 'window hypothesis' suggests they become harmful.",
    "The hepatic venous pressure gradient (HVPG) response to beta-blockers predicts outcomes — a decrease to <12 mmHg or >20% reduction from baseline is considered a good response.",
    "Varices are present in approximately 50% of patients at cirrhosis diagnosis — esophageal varices develop at a rate of 5-12% per year in those without them.",
    "Large esophageal varices carry a 15-20% risk of first variceal hemorrhage per year — band ligation or non-selective beta-blockers are used for primary prophylaxis.",
    "Variceal hemorrhage has a 6-week mortality of 15-25% — acute management includes restrictive transfusion, vasoactive drugs (octreotide/terlipressin), antibiotics, and emergent endoscopy.",
    "Transjugular intrahepatic portosystemic shunt (TIPS) creates a channel between portal and hepatic veins, reducing portal pressure — used for refractory ascites and recurrent variceal bleeding.",
    "TIPS is effective but can worsen hepatic encephalopathy in 25-45% of patients due to shunting portal blood (and ammonia) past the liver.",
    "Liver transplantation is the definitive treatment for decompensated cirrhosis — 1-year survival exceeds 90% at experienced centers.",
    "Living donor liver transplantation is possible because both the donated lobe and remnant liver regenerate to near-normal volume within weeks to months.",
    "Acute-on-chronic liver failure (ACLF) is a syndrome of acute deterioration in a patient with chronic liver disease — characterized by organ failures and high short-term mortality.",
    "The CLIF-SOFA score identifies ACLF and grades its severity (1-3) based on the number of organ failures — ACLF-3 has >80% 28-day mortality.",
    "Infections are the most common trigger for ACLF, followed by active alcoholism, GI hemorrhage, and in many cases, no identifiable precipitant.",
    "Systemic inflammation plays a central role in ACLF — elevated white blood cell count, C-reactive protein, and pro-inflammatory cytokines correlate with severity.",
    "Cirrhosis-associated immune dysfunction (CAID) involves both immunodeficiency (susceptibility to infections) and systemic inflammation (driving organ damage).",
    "Bacterial translocation — movement of gut bacteria or their products across the intestinal barrier into the bloodstream — is a key driver of complications in cirrhosis.",
    "Gut dysbiosis in cirrhosis features reduced diversity, increased potentially pathogenic bacteria, and decreased beneficial species — this worsens with disease severity.",
    "Zinc deficiency is common in cirrhosis (60-80%) and contributes to hepatic encephalopathy, immune dysfunction, and altered taste/appetite — supplementation may help.",
    "Vitamin D deficiency occurs in >90% of patients with advanced cirrhosis and is associated with increased mortality and infection risk.",
    "Bone disease (hepatic osteodystrophy) affects 12-55% of cirrhosis patients — osteoporosis is more common than osteomalacia and increases fracture risk.",
    "Cirrhosis is associated with increased risk of falls due to sarcopenia, encephalopathy, autonomic dysfunction, and medication effects — hip fracture mortality is doubled.",
    "Fatigue is the most common symptom in cirrhosis, affecting up to 70% of patients — it's multifactorial and often disproportionate to disease severity.",
    "Pruritus in cholestatic liver diseases can be debilitating — treatment escalates from cholestyramine to rifampicin, naltrexone, sertraline, and in severe cases, plasmapheresis or liver transplant.",
    "Sleep disturbances affect 40-60% of cirrhosis patients — inverted sleep-wake cycle (sleeping by day, awake at night) may be an early sign of encephalopathy.",
    "Sexual dysfunction is common in cirrhosis — erectile dysfunction affects up to 80% of men; reduced libido and irregular menses affect women.",
    "Hepatopulmonary syndrome involves intrapulmonary vascular dilations causing hypoxemia in liver disease — diagnosed by contrast echocardiography showing late passage of bubbles to the left heart.",
    "Portopulmonary hypertension is pulmonary arterial hypertension associated with portal hypertension — affects 5-10% of transplant candidates and affects transplant eligibility.",
    "Cirrhotic patients have impaired response to vaccination — higher doses or additional booster doses may be needed for hepatitis A, hepatitis B, pneumococcal, and influenza vaccines.",
]

# ═══════════════════════════════════════════════════════════════════════════════
# LIVER FAILURE — Acute & Chronic (Facts 251-500)
# ═══════════════════════════════════════════════════════════════════════════════
LIVER_FAILURE = [
    "Acute liver failure (ALF) is defined as severe liver injury with coagulopathy (INR ≥1.5) and hepatic encephalopathy in a patient without pre-existing liver disease, within 26 weeks of symptom onset.",
    "Acetaminophen (paracetamol) overdose is the most common cause of acute liver failure in the United States and United Kingdom.",
    "The toxic dose of acetaminophen is generally considered to be >150 mg/kg or >7.5-10g in adults — but chronic alcohol users and fasting patients may develop toxicity at lower doses.",
    "N-acetylcysteine (NAC) is the antidote for acetaminophen toxicity — it replenishes glutathione stores and is most effective when given within 8 hours of ingestion.",
    "NAC is also beneficial in non-acetaminophen acute liver failure — it improves transplant-free survival in early (grade 1-2) hepatic encephalopathy regardless of cause.",
    "The King's College Criteria predict the need for liver transplantation in ALF — separate criteria exist for acetaminophen (pH, INR, creatinine, encephalopathy grade) and non-acetaminophen causes.",
    "For acetaminophen ALF, arterial pH <7.30 after resuscitation (or combination of INR >6.5, creatinine >3.4 mg/dL, and grade 3-4 encephalopathy) predicts death without transplant.",
    "Hyperacute liver failure (onset <7 days) paradoxically has better spontaneous survival than subacute (onset 5-12 weeks), likely because the rapid onset reflects a more recoverable insult.",
    "Cerebral edema complicates 75-80% of grade 4 hepatic encephalopathy in ALF and is the leading cause of death — it's rare in chronic liver failure.",
    "Intracranial pressure monitoring may be used in ALF with deep coma — sustained ICP >25 mmHg or cerebral perfusion pressure <50 mmHg indicates poor prognosis.",
    "Amanita phalloides (death cap mushroom) poisoning causes ALF through amatoxin-mediated RNA polymerase II inhibition — mortality is 10-30% with aggressive treatment.",
    "Drug-induced liver injury (DILI) is the second most common cause of ALF in the US after acetaminophen — antibiotics, NSAIDs, and anticonvulsants are common culprits.",
    "Idiosyncratic DILI is unpredictable and not dose-dependent — it may involve immune-mediated mechanisms and genetic polymorphisms in drug metabolism.",
    "Hy's Law states that a drug causing hepatocellular injury (ALT >3x ULN) with jaundice (bilirubin >2x ULN) without biliary obstruction carries approximately 10% mortality from liver failure.",
    "Acute fatty liver of pregnancy (AFLP) causes ALF in the third trimester — immediate delivery is curative; maternal mortality has decreased from 75% to <10% with early recognition.",
    "HELLP syndrome (Hemolysis, Elevated Liver enzymes, Low Platelets) can cause severe liver dysfunction in pregnancy — it overlaps with AFLP and requires delivery.",
    "Hepatic ischemia ('shock liver') causes massive transaminase elevation (often >5000 U/L) with rapid rise and fall — usually due to cardiac failure, sepsis, or hemorrhage.",
    "Wilson disease can present as acute liver failure in young patients — Coombs-negative hemolytic anemia and very low alkaline phosphatase are clues; the ALP:bilirubin ratio <4 and AST:ALT ratio >2.2 suggest Wilson.",
    "Acute Budd-Chiari syndrome presents with rapid-onset hepatomegaly, ascites, and liver failure — anticoagulation, TIPS, or emergency transplant may be needed.",
    "Herpes simplex hepatitis is a rare but often fatal cause of ALF — it occurs in immunosuppressed patients and pregnant women; empiric acyclovir should be started if suspected.",
    "Autoimmune hepatitis can present as acute liver failure — corticosteroids may induce remission and avoid transplant in some cases, but should not delay listing.",
    "Liver failure impairs glucose homeostasis — hypoglycemia occurs because the liver can no longer perform gluconeogenesis or glycogenolysis; 10% dextrose infusion is often needed.",
    "Coagulopathy in liver failure involves decreased synthesis of both pro-coagulant (factors II, V, VII, IX, X) and anti-coagulant (protein C, S, antithrombin) factors.",
    "Factor V level is particularly useful in ALF prognosis — a level <20% of normal predicts poor outcome and is used in Clichy criteria for transplant listing.",
    "Fresh frozen plasma should NOT be given routinely to correct INR in liver failure unless there is active bleeding — it obscures the INR trend which is a key prognostic marker.",
    "Vitamin K should be administered in ALF — if INR improves within 24 hours, malnutrition/cholestasis is contributing; if not, it confirms true hepatic synthetic failure.",
    "Disseminated intravascular coagulation (DIC) can occur in ALF — distinguished from liver failure alone by very low fibrinogen, elevated D-dimer, and consumption of platelets.",
    "Lactic acidosis in ALF reflects both decreased hepatic lactate clearance and increased production from tissue hypoperfusion — arterial lactate >3.5 mmol/L after resuscitation predicts death.",
    "Acute kidney injury complicates 40-80% of ALF — mechanisms include direct nephrotoxicity (acetaminophen), hypovolemia, and acute tubular necrosis.",
    "Continuous renal replacement therapy (CRRT) is preferred over intermittent hemodialysis in ALF due to better hemodynamic stability and continuous ammonia clearance.",
    "Infection complicates up to 80% of ALF cases — prophylactic antibiotics and antifungals are considered in many centers, though evidence is limited.",
    "Seizures occur in 20-30% of ALF with cerebral edema — prophylactic phenytoin was historically used but is no longer routinely recommended.",
    "Hypothermia (core temp 33-35°C) has been used in ALF to reduce cerebral edema and intracranial pressure, though evidence from randomized trials is lacking.",
    "Hypertonic saline (targeting sodium 145-155 mEq/L) can prevent cerebral edema in ALF — it creates an osmotic gradient that reduces brain water content.",
    "The liver support device MARS (Molecular Adsorbent Recirculating System) removes albumin-bound toxins but has not demonstrated survival benefit in randomized trials for ALF.",
    "High-volume plasma exchange (removing and replacing 8-12 liters) has shown survival benefit in ALF in the FULMAR trial — it removes inflammatory mediators and replaces clotting factors.",
    "Auxiliary liver transplantation places a partial graft alongside the native liver — if the native liver regenerates, immunosuppression can be withdrawn.",
    "Emergency liver transplantation for ALF achieves 1-year survival of 65-80% — lower than elective transplant due to the critical condition of recipients and less optimal donor matching.",
    "Chronic liver failure is distinguished from ALF by the presence of underlying chronic liver disease — it develops insidiously over months to years.",
    "End-stage liver disease (ESLD) manifests with portal hypertension, synthetic failure, and complications: ascites, variceal bleeding, encephalopathy, hepatorenal syndrome.",
    "The 'sick liver' has impaired immune function — neutrophil dysfunction, complement deficiency, and reduced reticuloendothelial clearance increase infection susceptibility 4-fold.",
    "Adrenal insufficiency (hepatoadrenal syndrome) occurs in 50-70% of critically ill cirrhosis patients — low-dose hydrocortisone may improve hemodynamics in vasopressor-dependent shock.",
    "Hyponatremia in cirrhosis is dilutional — caused by non-osmotic release of ADH (vasopressin) in response to decreased effective arterial blood volume. Water restriction, not salt supplementation, is treatment.",
    "Severe hyponatremia (Na <125 mEq/L) in cirrhosis is associated with 30-day mortality of 25% and is an indication for transplant prioritization via MELD-Na.",
    "Rapid correction of hyponatremia risks osmotic demyelination syndrome (central pontine myelinolysis) — correction should not exceed 8-10 mEq/L per 24 hours.",
    "Vaptans (vasopressin V2 receptor antagonists, e.g., tolvaptan) can raise sodium in cirrhotic hyponatremia but are limited by hepatotoxicity concerns and cost.",
    "Ammonia levels correlate poorly with encephalopathy severity in chronic liver failure — treatment should be based on clinical assessment, not ammonia levels alone.",
    "Lactulose dose is titrated to achieve 2-3 soft bowel movements per day — under-dosing is ineffective, over-dosing causes dehydration and electrolyte disturbances.",
    "Precipitants of hepatic encephalopathy include infection, GI bleeding, constipation, electrolyte imbalance, excess dietary protein, sedative drugs, and dehydration.",
    "Overt hepatic encephalopathy is an indication for liver transplant evaluation — patients with recurrent episodes despite lactulose and rifaximin have poor prognosis.",
    "The liver normally clears approximately 85% of ammonia from portal blood via the urea cycle — in cirrhosis, portosystemic shunting bypasses this mechanism.",
    "Skeletal muscle is an alternative site for ammonia metabolism (via glutamine synthetase) — sarcopenia thus worsens hyperammonemia and encephalopathy.",
    "L-ornithine L-aspartate (LOLA) provides substrates for hepatic urea synthesis and muscle glutamine synthesis — it may reduce ammonia levels but evidence for clinical benefit is mixed.",
    "Polyethylene glycol (MiraLAX) has shown faster resolution of overt hepatic encephalopathy than lactulose in some trials, likely through more rapid gut clearance.",
    "Flumazenil can briefly improve encephalopathy by blocking endogenous benzodiazepine-like substances — but the effect is temporary and it's not a standard treatment.",
    "Manganese deposition in the globus pallidus (visible on T1-weighted MRI as hyperintensity) occurs in chronic liver failure and may contribute to extrapyramidal symptoms.",
    "Acquired hepatocerebral degeneration is a rare complication of chronic portosystemic shunting — it presents with parkinsonism, ataxia, and cognitive decline that may be irreversible.",
    "Liver failure causes immunoparesis — impaired opsonization, reduced complement (especially C3 and C4), neutrophil dysfunction, and defective monocyte Fc-receptor function.",
    "Spontaneous bacteremia occurs in 5-10% of hospitalized cirrhosis patients even without SBP — most common organisms are E. coli, Klebsiella, and Streptococcus species.",
    "Fungal infections are increasingly recognized in advanced liver failure — Candida and Aspergillus should be considered in patients failing antibiotic therapy.",
    "C-reactive protein and procalcitonin may be less reliable markers of infection in cirrhosis — baseline CRP is often elevated and procalcitonin can be falsely positive.",
    "The 'cirrhotic cardiomyopathy' includes prolonged QTc interval (>440ms in men, >460ms in women) found in 30-60% of cirrhosis patients — it normalizes after liver transplant.",
    "Hepatic hydrothorax is a pleural effusion (usually right-sided) in cirrhosis patients due to passage of ascitic fluid through diaphragmatic defects — it can occur without clinically apparent ascites.",
    "Hepatic hydrothorax is managed like ascites (salt restriction, diuretics) — chest tube placement is avoided due to high complication rates and should be temporary if used.",
    "Umbilical hernias are common in cirrhosis with ascites (20%) — incarceration risk is significant but surgical repair carries high mortality in decompensated patients.",
    "Cirrhosis increases the risk of venous thromboembolism (DVT/PE) — the old paradigm of 'auto-anticoagulation' is incorrect; prophylactic anticoagulation should be considered in hospitalized patients.",
    "Portal vein thrombosis occurs in 10-25% of cirrhosis patients — it can worsen portal hypertension and complicate transplantation.",
    "Anticoagulation for portal vein thrombosis in cirrhosis can achieve recanalization in 40-50% of cases — it's especially important when transplant is being considered.",
    "Relative adrenal insufficiency in cirrhosis is diagnosed by a cortisol increase <9 μg/dL after ACTH stimulation — it's associated with vasopressor-refractory shock.",
    "Total cortisol levels are unreliable in cirrhosis because of low cortisol-binding globulin (CBG) — free cortisol or salivary cortisol may be more accurate.",
    "Diuretic-resistant ascites affects approximately 10% of cirrhosis patients with ascites — defined as failure to respond to maximum doses of spironolactone (400mg) and furosemide (160mg).",
    "Midodrine (alpha-1 agonist) at 7.5-12.5mg TID may improve renal function and reduce large-volume paracentesis frequency in cirrhosis by increasing effective arterial volume.",
    "Clonidine and other centrally-acting agents should be avoided in cirrhosis — they can worsen encephalopathy and hypotension.",
    "Proton pump inhibitors increase the risk of SBP and hepatic encephalopathy in cirrhosis — they should only be used when clearly indicated (active peptic ulcer, severe GERD).",
    "Malnutrition affects 20-60% of cirrhosis patients and is associated with increased complications, impaired quality of life, and higher mortality.",
    "Nutritional assessment in cirrhosis is challenging — BMI is unreliable due to fluid retention; handgrip strength and mid-arm muscle circumference are better indicators.",
    "Late evening snack (50g complex carbohydrate) reduces protein catabolism overnight in cirrhosis — the 'overnight fast' in these patients resembles prolonged starvation in healthy individuals.",
    "Cirrhosis patients should consume 25-35 kcal/kg/day and 1.2-1.5 g protein/kg/day — divided into 4-6 small meals including a late evening snack.",
    "Immune-mediated thrombocytopenia can occur alongside cirrhosis-related thrombocytopenia — platelet-associated antibodies may be present and respond to steroids or TPO agonists.",
    "Thrombopoietin receptor agonists (avatrombopag, lusutrombopag) can raise platelet counts before procedures in cirrhosis, avoiding the need for platelet transfusion.",
    "Transfusion thresholds in cirrhosis: platelets >50,000 for major procedures, hemoglobin 7-8 g/dL target (over-transfusion worsens portal pressure and variceal bleeding).",
    "Viscoelastic testing (TEG/ROTEM) better reflects actual hemostatic capacity in cirrhosis than conventional INR — it may reduce unnecessary blood product use.",
    "Liver transplant evaluation includes psychosocial assessment — active substance use, social support, adherence potential, and mental health are critical factors.",
    "MELD exception points are granted for conditions not well-captured by laboratory scores — including HCC, hepatopulmonary syndrome, and refractory pruritus.",
    "Post-transplant survival in the US: 1-year 92%, 3-year 85%, 5-year 78%, 10-year 65% — recurrent disease (HCV, alcohol, NAFLD) and complications of immunosuppression are main long-term concerns.",
    "Alcohol-related liver disease patients typically require 6 months of documented sobriety before transplant listing — though this '6-month rule' is increasingly debated for select patients with ACLF.",
    "Recidivism (return to alcohol use) after liver transplant occurs in 15-40% of patients — careful pre-transplant selection and post-transplant support programs are essential.",
    "Split-liver transplantation divides a cadaveric liver into left lateral segment (for a child) and extended right lobe (for an adult) — maximizing the number of recipients from one donor.",
    "Machine perfusion of donor livers (normothermic or hypothermic) is expanding the usable donor pool by allowing assessment and reconditioning of marginal grafts.",
    "Immunosuppression after liver transplant typically includes a calcineurin inhibitor (tacrolimus) with or without mycophenolate — steroids are often weaned within months.",
    "De novo malignancy risk is increased 2-3 fold after liver transplant due to immunosuppression — skin cancer and lymphoproliferative disorders are most common.",
    "The liver is relatively immunoprivileged — operational tolerance (withdrawal of all immunosuppression without rejection) has been achieved in 20-40% of carefully selected long-term transplant recipients.",
]

# ═══════════════════════════════════════════════════════════════════════════════
# PARACENTESIS (Facts 501-750)
# ═══════════════════════════════════════════════════════════════════════════════
PARACENTESIS = [
    "Paracentesis is the procedure of inserting a needle or catheter into the peritoneal cavity to remove ascitic fluid — it can be diagnostic (small volume) or therapeutic (large volume).",
    "Diagnostic paracentesis should be performed in all patients with new-onset ascites and in all hospitalized patients with ascites to rule out spontaneous bacterial peritonitis.",
    "The most common site for paracentesis is the left lower quadrant, approximately 3cm cephalad and 3cm medial to the anterior superior iliac spine.",
    "Ultrasound guidance for paracentesis reduces the risk of complications and failed attempts — it's recommended when ascites is moderate or the patient is obese.",
    "Large-volume paracentesis (LVP) refers to removal of more than 5 liters of ascitic fluid in a single session — it provides rapid relief of abdominal distension and respiratory compromise.",
    "There is no upper limit to the volume that can be safely removed during LVP when albumin replacement is given — 10-20+ liters can be drained in a single session.",
    "Albumin infusion (6-8g per liter removed) should be given when more than 5 liters are removed during LVP to prevent post-paracentesis circulatory dysfunction (PPCD).",
    "Post-paracentesis circulatory dysfunction is characterized by activation of the renin-angiotensin-aldosterone system — it occurs in 60-80% of patients if albumin is not given after LVP >5L.",
    "PPCD is associated with faster recurrence of ascites, development of hepatorenal syndrome, dilutional hyponatremia, and increased mortality.",
    "Albumin is superior to other plasma expanders (dextran, polygeline, saline) for preventing PPCD after LVP >5L — alternatives may be acceptable for smaller volumes.",
    "For removal of less than 5 liters, albumin infusion is not strictly required — but many practitioners give it regardless due to the low cost relative to potential complications.",
    "Paracentesis is one of the safest procedures in medicine — significant complications occur in less than 1% of procedures even in patients with coagulopathy.",
    "Routine correction of coagulopathy (transfusing FFP or platelets) before paracentesis is NOT recommended — studies show no increase in bleeding complications with INR up to 8-9.",
    "Hemorrhagic complications of paracentesis include abdominal wall hematoma (0.5-1%), hemoperitoneum (<0.1%), and pseudoaneurysm of the inferior epigastric artery (very rare).",
    "The inferior epigastric artery runs approximately 5cm lateral to the midline — paracentesis sites should avoid this area to prevent arterial injury.",
    "Bowel perforation during paracentesis is extremely rare (<0.1%) — risk is increased with extensive adhesions from prior surgery, severe bowel distension, or large hernias.",
    "Persistent ascitic fluid leakage from the puncture site occurs in approximately 5% of procedures — it's managed with a single purse-string suture, ostomy bag, or repositioning.",
    "A Z-track technique (displacing the skin and subcutaneous tissue before needle insertion) reduces post-procedure leakage by creating an oblique track that seals when the needle is removed.",
    "The ascitic fluid should be sent for cell count with differential, albumin, total protein, and culture (in blood culture bottles at bedside) at minimum.",
    "Serum-ascites albumin gradient (SAAG) = serum albumin minus ascitic fluid albumin — a gradient ≥1.1 g/dL indicates portal hypertension with 97% accuracy.",
    "SAAG ≥1.1 g/dL causes include cirrhosis, cardiac ascites, Budd-Chiari syndrome, portal vein thrombosis, and myxedema.",
    "SAAG <1.1 g/dL causes include peritoneal carcinomatosis, tuberculous peritonitis, pancreatic ascites, nephrotic syndrome, and serositis.",
    "Ascitic fluid total protein <1.5 g/dL indicates high risk for SBP — these patients benefit from primary antibiotic prophylaxis.",
    "Ascitic fluid total protein >2.5 g/dL suggests cardiac ascites (along with SAAG ≥1.1) — the high protein results from hepatic congestion increasing protein transudation.",
    "Neutrophil count ≥250 cells/mm³ in ascitic fluid diagnoses SBP even before culture results — empiric antibiotics should be started immediately.",
    "Ascitic fluid culture is positive in only 40% of SBP cases — inoculating fluid directly into blood culture bottles at bedside increases yield to 60-80%.",
    "Monomicrobial non-neutrocytic bacterascites (positive culture, PMN <250) may resolve spontaneously — repeat paracentesis in 48 hours to determine if treatment is needed.",
    "Culture-negative neutrocytic ascites (PMN ≥250, negative culture) should be treated as SBP — culture negativity is often due to low bacterial load.",
    "Secondary bacterial peritonitis (from perforation/abscess) is distinguished from SBP by: multiple organisms on culture, very high PMN count, ascitic glucose <50 mg/dL, protein >1 g/dL, LDH > serum level.",
    "Bloody ascitic fluid (RBC >10,000/mm³) requires correction of the PMN count: subtract 1 PMN for every 250 RBCs to determine the 'true' PMN count for SBP diagnosis.",
    "Malignant ascites typically has low SAAG (<1.1), elevated protein, elevated LDH, and positive cytology — cytology has sensitivity of 60-90% for peritoneal carcinomatosis.",
    "Chylous ascites (milky appearing, triglycerides >200 mg/dL) results from lymphatic disruption — causes include lymphoma, surgery, trauma, and tuberculosis.",
    "Pancreatic ascites has very elevated amylase (>1000 U/L) and protein — it results from pancreatic duct disruption or leaking pseudocyst.",
    "Tuberculous peritonitis has high protein, high LDH, lymphocytic predominance, and low glucose in ascitic fluid — ascitic ADA (adenosine deaminase) >30 U/L is suggestive.",
    "Triglyceride levels should be checked in milky/turbid ascitic fluid — chylous ascites (TG >200 mg/dL) has a different differential than infected or malignant ascites.",
    "Gram stain of ascitic fluid has low sensitivity for SBP (10-30%) — treatment decisions should be based on cell count, not Gram stain.",
    "The optimal needle for diagnostic paracentesis is a 22-gauge, 1.5-inch (3.8cm) needle for thin patients, or a longer spinal needle for obese patients.",
    "For therapeutic (large-volume) paracentesis, an 8-French pigtail catheter or metal cannula with a drainage bag provides safer, more efficient drainage than repeated needle insertions.",
    "Paracentesis can be safely performed in the midline (linea alba) when lateral sites are inaccessible — the bladder should be decompressed first.",
    "Timing of albumin infusion: it should be given during or immediately after LVP, not hours later — delayed administration may not prevent PPCD.",
    "25% albumin is preferred for post-paracentesis replacement — the usual prescription is 25g (100mL of 25%) per 2-3 liters removed, starting after the first 5 liters.",
    "Serial therapeutic paracentesis every 1-2 weeks is safe and effective for refractory ascites — many patients manage this as outpatients.",
    "Indwelling peritoneal catheters (e.g., PleurX drains adapted for ascites) allow home drainage and reduce hospital visits — infection risk is approximately 5-10% per year.",
    "Automated low-flow ascites pumps (alfapump) continuously pump ascites into the bladder for urinary excretion — they reduce paracentesis frequency but have a high complication rate.",
    "Paracentesis provides immediate symptomatic relief — improvement in dyspnea, early satiety, and abdominal discomfort is usually within hours.",
    "Renal function should be monitored after LVP — creatinine may rise if PPCD occurs, typically within 24-72 hours of the procedure.",
    "Diuretics should generally be held on the day of LVP and can be resumed 24-48 hours later if the patient remains hemodynamically stable.",
    "The recurrence rate of ascites after LVP without ongoing diuretic therapy is rapid — most patients reaccumulate to their pre-tap volume within 1-2 weeks.",
    "Paracentesis is the procedure of choice for tense ascites — diuretics alone are too slow to relieve acute respiratory compromise or abdominal compartment syndrome.",
    "Abdominal compartment syndrome from massive ascites (intra-abdominal pressure >20 mmHg with organ dysfunction) is a medical emergency requiring immediate LVP.",
    "Local anesthesia with 1% lidocaine is sufficient for paracentesis — injection into skin and peritoneum along the planned tract minimizes discomfort.",
    "Complications specifically related to repeated paracentesis include protein depletion, worsening malnutrition, and theoretically increased infection risk — albumin replacement mitigates some of these.",
    "A diagnostic 'dry tap' (no fluid obtained) should prompt ultrasound-guided attempt — loculated ascites, very small volume, or incorrect needle placement are common reasons.",
    "Paracentesis-induced bacteremia is extremely rare (<1%) — routine antibiotic prophylaxis before paracentesis is not recommended.",
    "Hemoperitoneum after paracentesis (abdominal pain, hemodynamic instability, falling hematocrit) requires urgent imaging — CT angiography can identify bleeding vessels for embolization.",
    "Post-paracentesis hypotension not related to PPCD can occur from vasovagal reaction during the procedure — Trendelenburg position and IV fluid bolus are usually sufficient.",
    "The ascitic fluid appearance provides immediate clinical information: clear/straw-colored (uncomplicated), cloudy (infection/high cells), bloody (malignancy/trauma), milky (chylous).",
    "Cell count must be performed within 1-2 hours of collection (or refrigerated) — cells degrade in ascitic fluid, potentially giving falsely low counts.",
    "Bedside inoculation of blood culture bottles with ascitic fluid is critical — laboratory-based culture (sending fluid in a specimen cup) misses up to 60% of infections.",
    "Peritoneal fluid glucose below 50 mg/dL (or significantly lower than serum) suggests secondary peritonitis or tuberculous peritonitis rather than SBP.",
    "CEA >5 ng/mL and alkaline phosphatase >240 U/L in ascitic fluid strongly suggest secondary peritonitis (bowel perforation) rather than primary SBP.",
    "Cytology should be sent when malignant ascites is suspected — three separate specimens on different days increases sensitivity to >90% for peritoneal carcinomatosis.",
    "Ascitic amylase >3x serum level suggests pancreatic ascites or gut perforation — further imaging with CT is warranted.",
    "Paracentesis in the setting of DIC or severe thrombocytopenia (<20,000) may warrant platelet or factor support — but the bleeding risk remains very low.",
    "Abdominal wall collateral vessels (from portal hypertension) are visible on ultrasound — they should be avoided during paracentesis as they can bleed significantly.",
    "TIPS reduces the need for paracentesis in refractory ascites — ascites resolves completely in 50-75% and partially in another 10-20% of patients after TIPS.",
    "Paracentesis has been performed for centuries — the ancient Greeks described it; the modern technique with albumin replacement was established in the 1980s-90s.",
    "Same-day discharge after outpatient LVP with albumin is standard — patients do not need prolonged observation if they remain hemodynamically stable.",
    "Hepatic hydrothorax can be indirectly treated by paracentesis — reducing intra-abdominal pressure decreases fluid transit through diaphragmatic defects.",
    "Repeated LVP without albumin replacement leads to progressive renal impairment — even if PPCD is not immediately clinically apparent, subclinical activation of vasoconstrictors occurs.",
    "Ascitic fluid amylase, LDH, bilirubin, glucose, and triglycerides are 'second-line' tests ordered based on clinical suspicion — not needed for routine evaluation.",
    "The optimal timing for paracentesis in a newly admitted cirrhosis patient is within 12 hours of admission — delays in diagnosis of SBP increase mortality.",
]

# ═══════════════════════════════════════════════════════════════════════════════
# ORTHOSTATIC HYPOTENSION (Facts 751-1000)
# ═══════════════════════════════════════════════════════════════════════════════
ORTHOSTATIC_HYPOTENSION = [
    "Orthostatic hypotension (OH) is defined as a sustained reduction of systolic BP ≥20 mmHg or diastolic BP ≥10 mmHg within 3 minutes of standing from a supine position.",
    "In patients with supine hypertension (SBP ≥140), a threshold of ≥30 mmHg systolic drop is more appropriate for diagnosing orthostatic hypotension.",
    "Orthostatic hypotension affects approximately 20% of adults over age 65 and up to 30-50% of nursing home residents.",
    "In cirrhosis patients, orthostatic hypotension is extremely common (30-60%) due to splanchnic vasodilation, reduced effective circulating volume, and autonomic neuropathy.",
    "The mechanism of OH in cirrhosis involves excessive nitric oxide production, leading to splanchnic arterial vasodilation that 'steals' blood volume from the systemic circulation.",
    "Standing triggers the baroreceptor reflex: blood pools in lower extremities → reduced venous return → decreased cardiac output → baroreceptor activation → sympathetic outflow → vasoconstriction + increased heart rate.",
    "Autonomic failure disrupts this compensatory mechanism — the sympathetic nervous system fails to increase heart rate and vascular resistance adequately upon standing.",
    "Neurogenic orthostatic hypotension (nOH) results from failure of norepinephrine release from sympathetic neurons — HR fails to increase >15 bpm despite BP drop.",
    "Non-neurogenic OH results from volume depletion, medications, or cardiac causes — the heart rate typically increases >15 bpm as a compensatory response.",
    "Distinguishing neurogenic from non-neurogenic OH: if HR rise is <15 bpm with BP drop ≥30 mmHg systolic, neurogenic autonomic failure is likely.",
    "Common medications causing OH include: diuretics, alpha-blockers, antihypertensives, nitrates, antidepressants (TCAs, MAOIs), antipsychotics, opioids, and PDE5 inhibitors.",
    "In cirrhosis, paracentesis can transiently worsen orthostatic hypotension by further reducing effective circulating volume — albumin replacement helps prevent this.",
    "Post-paracentesis orthostatic symptoms (dizziness, lightheadedness on standing) are early signs of PPCD — blood pressure monitoring in supine and standing positions is warranted.",
    "Diuretics used for ascites management (spironolactone, furosemide) are a major contributor to OH in cirrhosis — dose reduction should be considered when OH symptoms appear.",
    "The pathophysiology of OH in cirrhosis involves: splanchnic vasodilation (primary) + hypoalbuminemia (reduced oncotic pressure) + autonomic neuropathy + diuretic use + anemia.",
    "Cirrhotic autonomic neuropathy affects both sympathetic and parasympathetic systems — manifesting as OH, impaired heart rate variability, gastroparesis, and erectile dysfunction.",
    "Symptoms of OH include: lightheadedness, dizziness, visual blurring, weakness, fatigue, cognitive impairment, neck/shoulder pain ('coat hanger' pain), and syncope.",
    "Coat hanger pain (aching in posterior neck and shoulders) is a specific symptom of OH — caused by ischemia of trapezius and neck muscles during upright posture.",
    "Falls are the most dangerous consequence of OH — they cause hip fractures, head injuries, and are associated with 2-3x increased mortality in elderly populations.",
    "OH is an independent predictor of cardiovascular events, stroke, heart failure, and all-cause mortality — even in younger populations.",
    "Initial orthostatic hypotension is a transient BP drop within 15 seconds of standing, often with compensatory tachycardia — it's common, usually benign, and caused by gravitational blood redistribution.",
    "Delayed orthostatic hypotension occurs after 3 minutes of standing — it's associated with mild autonomic dysfunction and may progress to classic OH over time.",
    "Postprandial hypotension (BP drop ≥20 mmHg within 2 hours of eating) often coexists with OH — splanchnic blood pooling after meals exacerbates the hemodynamic compromise.",
    "In cirrhosis, postprandial hypotension is worsened by portosystemic shunting — blood that should pass through the liver instead pools in the splanchnic bed.",
    "Supine hypertension coexisting with OH is a therapeutic challenge in cirrhosis — treating one typically worsens the other.",
    "OH assessment technique: patient rests supine for 5 minutes → measure BP and HR → patient stands → measure BP and HR at 1 and 3 minutes (and 5 minutes if delayed OH suspected).",
    "Tilt-table testing provides a controlled assessment of OH — the patient is tilted to 60-70° for up to 45 minutes with continuous BP and HR monitoring.",
    "Head-up tilt testing can provoke vasovagal syncope (neurocardiogenic syncope) — characterized by sudden bradycardia and hypotension after a period of standing.",
    "24-hour ambulatory blood pressure monitoring can identify OH episodes, nocturnal hypertension (common in autonomic failure), and non-dipping patterns.",
    "Non-pharmacological management of OH: arise gradually from supine (sit at edge of bed first), cross legs while standing, wear compression stockings, increase fluid and salt intake.",
    "Compression garments (waist-high stockings providing 30-40 mmHg, or abdominal binders) reduce venous pooling and can raise standing BP by 10-15 mmHg.",
    "Abdominal binders may be more effective than leg compression alone — the splanchnic circulation holds the largest venous reservoir in the body.",
    "Fluid intake of 2-3 liters daily (unless contraindicated by heart failure) helps expand plasma volume and reduce OH severity.",
    "Rapid water drinking (500mL within 5 minutes) can acutely raise BP by 20-30 mmHg within 5-15 minutes — useful as a 'rescue' before activities.",
    "Salt supplementation (1-2g of sodium chloride tablets, or liberal dietary salt) increases intravascular volume — BUT this is contraindicated in cirrhosis with ascites.",
    "In cirrhosis patients, the standard OH treatment of increased salt is contraindicated because it worsens ascites and edema — this makes management particularly challenging.",
    "Head-of-bed elevation (10-20° or 6 inches at the head) reduces nocturnal supine hypertension and nocturnal diuresis, improving morning orthostatic tolerance.",
    "Sleeping with the head elevated reduces renal perfusion pressure overnight → less nocturnal diuresis → better volume status in the morning → less OH upon arising.",
    "Physical counter-maneuvers: leg crossing with tensing, squatting, toe-raising, thigh clenching — these can acutely raise BP by 20-40 mmHg and abort presyncope.",
    "Small, frequent meals reduce postprandial hypotension — large carbohydrate-rich meals cause the greatest postprandial BP drops.",
    "Avoiding alcohol is important in OH management — alcohol causes vasodilation and volume depletion; this is especially relevant in cirrhosis patients.",
    "Caffeine (200-250mg, ~2 cups of coffee) before meals can attenuate postprandial hypotension by blocking adenosine-mediated splanchnic vasodilation.",
    "Hot environments, hot baths/showers, and prolonged standing worsen OH — patients should be counseled to sit down when symptomatic rather than trying to 'walk it off'.",
    "Exercise-induced OH can occur during or immediately after exertion — patients should cool down gradually and avoid abrupt cessation of activity.",
    "Midodrine (alpha-1 agonist) is first-line pharmacotherapy for OH — starting dose 2.5-5mg TID (with last dose ≥4 hours before bedtime to avoid supine hypertension).",
    "Midodrine raises standing BP by 15-25 mmHg and reduces OH symptoms — it works by constricting arterioles and venous capacitance vessels.",
    "Midodrine's main side effects: supine hypertension (monitor!), piloerection (goosebumps), scalp tingling, and urinary retention.",
    "In cirrhosis, midodrine at 7.5-12.5mg TID has been shown to improve effective arterial volume, renal function, and reduce large-volume paracentesis frequency.",
    "Midodrine may delay the need for TIPS in cirrhosis patients with refractory ascites — it partially counteracts the splanchnic vasodilation driving sodium retention.",
    "Droxidopa (norepinephrine prodrug) is FDA-approved for neurogenic OH — converted to norepinephrine peripherally; starting dose 100mg TID, titrate to 600mg TID.",
    "Droxidopa is less studied in cirrhosis-related OH — its hepatic metabolism raises concerns, though it may be useful in selected patients with clear neurogenic component.",
    "Fludrocortisone (synthetic mineralocorticoid) at 0.1-0.3mg daily expands plasma volume through renal sodium retention — it takes 1-2 weeks for full effect.",
    "Fludrocortisone is generally contraindicated in cirrhosis with ascites — it causes fluid retention that worsens ascites, edema, and hypokalemia.",
    "Pyridostigmine (acetylcholinesterase inhibitor) at 60mg BID-TID enhances ganglionic sympathetic transmission — it raises standing BP without worsening supine hypertension.",
    "Pyridostigmine may be better tolerated than midodrine in patients with coexisting supine hypertension — but its efficacy is more modest (5-10 mmHg increase).",
    "Atomoxetine (norepinephrine reuptake inhibitor) at 10-18mg BID raises standing BP in neurogenic OH — off-label use with promising preliminary results.",
    "Octreotide (somatostatin analog) can reduce postprandial and post-exercise hypotension by preventing splanchnic vasodilation — given as 25-50 mcg subcutaneously before meals.",
    "In cirrhosis, octreotide is used in variceal bleeding (reduces portal pressure) — its use for OH is limited but may have a dual benefit.",
    "Erythropoietin can improve OH in patients with anemia by increasing red blood cell mass and blood volume — particularly relevant in cirrhosis where anemia is common.",
    "Anemia worsens OH by reducing oxygen-carrying capacity and blood viscosity — maintaining hemoglobin >8-9 g/dL may improve orthostatic tolerance.",
    "Desmopressin (DDAVP) at bedtime can reduce nocturnal polyuria and improve morning orthostatic tolerance — but hyponatremia risk mandates monitoring, especially in cirrhosis.",
    "DDAVP is relatively contraindicated in cirrhosis due to the already dilutional hyponatremia from inappropriate ADH secretion — sodium must be closely monitored.",
    "Combination therapy is often needed for severe OH — a common regimen is midodrine + compression garments + head-of-bed elevation + adequate fluids.",
    "In cirrhosis specifically, the limited pharmacological options (no salt, no fludrocortisone, caution with many drugs) make non-pharmacological measures even more important.",
    "Albumin infusion in cirrhosis directly addresses OH by expanding intravascular volume — regular albumin therapy (weekly 40g IV) is being studied as long-term treatment.",
    "The ANSWER trial showed that long-term albumin administration (40g twice weekly) reduced mortality and complications in cirrhosis, partly through improved hemodynamics.",
    "Autonomic function testing in cirrhosis includes: Valsalva maneuver, deep breathing HR variability, cold pressor test, and quantitative sudomotor axon reflex testing (QSART).",
    "Valsalva ratio (max HR during strain / min HR after release) <1.21 suggests cardiac autonomic neuropathy — common in alcoholic and diabetic cirrhosis.",
    "Heart rate variability (HRV) is reduced in cirrhosis and correlates with disease severity — low HRV predicts mortality independently of MELD score.",
    "QTc prolongation in cirrhosis (part of cirrhotic cardiomyopathy) is associated with autonomic dysfunction and OH — it normalizes after liver transplantation.",
    "Post-liver transplant, OH typically improves within weeks to months as splanchnic vasodilation resolves and autonomic function recovers.",
    "Beta-blockers (used for portal hypertension prophylaxis) can worsen OH by preventing compensatory tachycardia — dose reduction or discontinuation may be needed.",
    "Carvedilol's alpha-blocking component can worsen OH more than pure beta-blockers (propranolol, nadolol) — this should be considered when choosing portal hypertension prophylaxis.",
    "The 'window' for beta-blocker benefit in cirrhosis closes with advancing disease — in refractory ascites or mean arterial pressure <82 mmHg, beta-blockers may increase mortality.",
    "Lactulose-induced diarrhea can worsen OH through volume depletion — balancing encephalopathy treatment with volume status is important.",
    "Hepatic encephalopathy itself can mask OH symptoms — confused patients may not report dizziness, making fall risk assessment by caregivers critical.",
    "OH increases hospital length of stay in cirrhosis patients — addressing it early in admission can improve mobilization and discharge planning.",
    "Sitting BP may underestimate the severity of OH — measurements should be taken in the supine position (after 5 minutes rest) for comparison with standing.",
    "In patients unable to stand (too weak, encephalopathic), sit-up challenge (supine to sitting with legs dangling) can identify those at risk for OH.",
    "OH after large-volume paracentesis is most pronounced 24-72 hours post-procedure — patients should be counseled about fall precautions during this window.",
    "Intra-procedure monitoring during paracentesis: if the patient becomes lightheaded, stop drainage, lower the head of bed, and consider IV albumin or saline bolus.",
    "Morning OH is typically worst because: overnight diuresis reduces volume, recumbency redistributes fluid centrally (lost upon standing), and cortisol is still ramping up.",
    "Patients with cirrhosis and OH should avoid standing immediately upon waking — sitting at the bed edge for 1-2 minutes with ankle pumps before standing reduces fall risk.",
    "Dehydration assessment in cirrhosis is challenging — traditional markers (BUN, skin turgor) are unreliable; orthostatic vitals and weight trends are more informative.",
    "Point-of-care ultrasound (IVC diameter and collapsibility) can help assess volume status in cirrhosis patients with OH — though interpretation is complicated by elevated right heart pressures.",
    "Falls prevention programs for cirrhosis patients should address: OH (volume, medications), sarcopenia (exercise, nutrition), encephalopathy (lactulose compliance), and environmental hazards.",
    "Wearable continuous BP monitors are emerging tools for tracking OH episodes throughout the day — they may help optimize timing of medications and activities.",
    "Orthostatic intolerance syndromes (POTS — postural orthostatic tachycardia syndrome) can coexist with or mimic OH — in POTS, HR rises >30 bpm without significant BP drop.",
    "POTS is not typical in cirrhosis — the excessive tachycardia response in cirrhosis is usually an appropriate compensatory mechanism for true volume depletion.",
    "Autonomic neuropathy in alcoholic liver disease may involve direct alcohol neurotoxicity, thiamine deficiency, and liver disease itself — nutritional repletion is important.",
    "Thiamine (vitamin B1) deficiency should be corrected in all patients with alcoholic liver disease — it contributes to autonomic neuropathy, cardiomyopathy, and Wernicke encephalopathy.",
    "Diabetes-related autonomic neuropathy frequently coexists with cirrhosis (NAFLD/NASH patients) — doubling the impact on orthostatic regulation.",
    "Glycemic control affects autonomic function — optimizing diabetes management may improve OH in cirrhosis patients with concurrent diabetes.",
    "Volume resuscitation for acute OH in hospitalized cirrhosis patients should use albumin rather than crystalloid — crystalloid rapidly third-spaces into ascites.",
    "Normal saline infusion in cirrhosis worsens ascites and edema without sustained intravascular expansion — albumin (20-25%) provides longer-lasting hemodynamic support.",
    "The goal of OH management in cirrhosis is symptom control and fall prevention — achieving 'normal' orthostatic response is often unrealistic in advanced disease.",
    "Documentation of orthostatic vitals should be part of routine nursing assessment for all hospitalized cirrhosis patients — identifying OH early prevents falls.",
    "Discharge planning for cirrhosis patients with OH should include: home BP monitoring education, fall-risk environment modification, medication reconciliation, and follow-up vitals check.",
    "Physical therapy consultation for progressive mobilization and balance training reduces fall risk in cirrhosis patients with OH and sarcopenia.",
    "Occupational therapy can recommend assistive devices (grab bars, raised toilet seats, shower chairs) that reduce fall risk when OH causes transient instability.",
    "Long-term prognosis: OH in cirrhosis generally worsens as liver disease progresses — definitive treatment is liver transplantation, which reverses the hemodynamic derangements.",
]

# ═══════════════════════════════════════════════════════════════════════════════
# INGEST
# ═══════════════════════════════════════════════════════════════════════════════
ALL_FACTS = CIRRHOSIS_GENERAL + LIVER_FAILURE + PARACENTESIS + ORTHOSTATIC_HYPOTENSION

if __name__ == "__main__":
    log(f"Starting ingest of {len(ALL_FACTS)} medical facts about liver disease...")
    log(f"  Cirrhosis: {len(CIRRHOSIS_GENERAL)} facts")
    log(f"  Liver Failure: {len(LIVER_FAILURE)} facts")
    log(f"  Paracentesis: {len(PARACENTESIS)} facts")
    log(f"  Orthostatic Hypotension: {len(ORTHOSTATIC_HYPOTENSION)} facts")

    for i, fact in enumerate(ALL_FACTS, 1):
        remember(fact)
        if i % 50 == 0:
            elapsed = time.time() - start_time
            rate = count / elapsed if elapsed > 0 else 0
            log(f"  Progress: {i}/{len(ALL_FACTS)} ({count} ok, {failed} failed, {rate:.1f}/s)")
        time.sleep(0.05)  # Rate limit to avoid overwhelming memory server

    elapsed = time.time() - start_time
    summary = f"✅ Liver disease knowledge ingest complete: {count}/{len(ALL_FACTS)} facts stored ({failed} failed) in {elapsed:.0f}s"
    log(summary)

    if count > 0:
        try:
            slack_post(f"```\n📚 Medical Knowledge Ingest\n\n{summary}\n\nTopics: Cirrhosis, Liver Failure, Paracentesis, Orthostatic Hypotension\n—N\n```")
        except:
            log("(Slack notification skipped)")
