#!/usr/bin/env python3
"""Tests for nova_publish_journal.py — the 7 house categories (Security, Performance, Retry, Unit,
Integration, Functional, Frame). Written by Jordan Koch (via Claude).

The Hugo tree and LOG_FILE live in a tempdir, git is a mocked subprocess.run, and the tag extractor /
cross-linker are stub modules (patched per test with patch.dict, so nothing reaches an LLM)."""
import importlib.util
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import time
import types
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest.mock import MagicMock, patch

SCRIPTS = Path(__file__).resolve().parents[1]
SCRIPT = SCRIPTS / "nova_publish_journal.py"
SRC = SCRIPT.read_text()
sys.path.insert(0, str(SCRIPTS))


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


pj = _load("nova_publish_journal_t", SCRIPT)


def _cp(rc=0, out="", err=""):
    return subprocess.CompletedProcess([], rc, stdout=out, stderr=err)


class GitShell:
    def __init__(self, commit=(0, ""), pull=0, push=0):
        self.commit, self.pull, self.push, self.calls = commit, pull, push, []

    def __call__(self, argv, **kw):
        self.calls.append(argv[1])
        return {"add": _cp(), "commit": _cp(self.commit[0], self.commit[1]), "pull": _cp(self.pull, err="conflict"),
                "rebase": _cp(), "push": _cp(self.push, err="rejected")}[argv[1]]


class _Base(unittest.TestCase):
    def setUp(self):
        self.td = tempfile.TemporaryDirectory()
        self.addCleanup(self.td.cleanup)
        root = Path(self.td.name) / "nova-journal"
        tags = types.ModuleType("nova_tag_extractor")
        tags.extract_tags = MagicMock(return_value=["space", "orbits"])
        linker = types.ModuleType("nova_cross_linker")
        linker.find_related = MagicMock(return_value=[{"x": 1}])
        linker.format_related_frontmatter = MagicMock(return_value='related: ["a"]')
        self.tags, self.linker = tags, linker
        self.git = GitShell()
        patches = [patch.object(pj, "HUGO_ROOT", root),
                   patch.object(pj, "CONTENT_DREAMS", root / "content/dreams"),
                   patch.object(pj, "CONTENT_ESSAYS", root / "content/essays"),
                   patch.object(pj, "IMAGES_DREAMS", root / "static/images/dreams"),
                   patch.object(pj, "IMAGES_ESSAYS", root / "static/images/essays"),
                   patch.object(pj, "LOG_FILE", Path(self.td.name) / "publish.log"),
                   patch.dict(sys.modules, {"nova_tag_extractor": tags, "nova_cross_linker": linker}),
                   patch.object(pj.subprocess, "run", self.git)]
        for p in patches:
            p.start()
            self.addCleanup(p.stop)
        self.out = io.StringIO()
        r = redirect_stdout(self.out)
        r.__enter__()
        self.addCleanup(r.__exit__, None, None, None)
        self.root = root

    def dream_file(self, extra=""):
        d = Path(self.td.name) / "2026-05-04.md"
        d.write_text('# Dream Journal — May 4\n*Theme: "Glass Tides"*\nTheme: "Glass Tides"\nMood: wistful\n'
                     f"I walked on water.\n{extra}*Generated by Nova*\n")
        return d


class TestSecurity(_Base):
    def test_no_hardcoded_credentials(self):
        pat = re.compile(r"(api[_-]?key|password|secret|token)\s*=\s*['\"][A-Za-z0-9+/]{16,}['\"]", re.I)
        self.assertIsNone(pat.search(SRC))

    def test_emails_and_home_paths_scrubbed(self):
        addr = "kochj23" + "@" + "gmail.com"
        nova = next(iter(pj.SAFE_EMAILS))          # Nova's own address is the one allowed through
        self.assertEqual(pj.scrub_emails(f"mail {addr} or {nova}"), f"mail [email redacted] or {nova}")
        pj.publish_dream(str(self.dream_file(f"see {Path.home()}/secret.txt\nwrite {addr}\n")))
        post = (self.root / "content/dreams/2026-05-04.md").read_text()
        self.assertNotIn(str(Path.home()), post)
        self.assertNotIn(addr, post)

    def test_git_is_argv_not_shell(self):
        self.assertNotIn("shell=True", SRC)


class TestPerformance(_Base):
    def test_scrub_large_text_fast(self):
        text = " ".join(f"user{i}@example.com word" for i in range(10_000))
        t0 = time.perf_counter()
        out = pj.scrub_emails(text)
        self.assertLess(time.perf_counter() - t0, 1.0)
        self.assertEqual(out.count("[email redacted]"), 10_000)


class TestRetry(_Base):
    def test_diverged_repo_aborts_rebase_and_never_pushes(self):
        # RETRY GAP: git_push — one pull --rebase attempt; on conflict it aborts the rebase and skips push
        self.git.pull = 1
        pj.git_push("msg")
        self.assertEqual(self.git.calls, ["add", "commit", "pull", "rebase"])
        self.assertIn("Push ABORTED", self.out.getvalue())

    def test_push_failure_and_git_exception_fail_open(self):
        self.git.push = 1
        pj.git_push("msg")
        self.assertIn("Push FAILED", self.out.getvalue())
        with patch.object(pj.subprocess, "run", side_effect=OSError("no git")):
            pj.git_push("msg")
        self.assertIn("Git error: no git", self.out.getvalue())


class TestUnit(_Base):
    def test_nothing_to_commit_stops_early(self):
        self.git.commit = (1, "nothing to commit, working tree clean")
        pj.git_push("m")
        self.assertEqual(self.git.calls, ["add", "commit"])

    def test_tag_fallback_on_extractor_failure(self):
        self.tags.extract_tags.side_effect = RuntimeError("llm down")
        self.assertEqual(pj._get_tags("t", "x", "essays"), ["essay", "culture"])
        self.assertEqual(pj._get_tags("t", "x", "nope"), ["journal"])
        self.linker.find_related.side_effect = RuntimeError("pg down")
        self.assertEqual(pj._get_related("x", "essays", "s"), "")

    def test_missing_dream_file(self):
        self.assertFalse(pj.publish_dream(str(Path(self.td.name) / "missing.md")))
        self.assertEqual(self.git.calls, [])


class TestIntegration(_Base):
    def test_uses_shared_tagger_and_linker(self):
        pj.publish_essay("Orbits", "astronomy", "Body text.")
        self.assertEqual(self.tags.extract_tags.call_args.args[2], "essays")
        self.assertEqual(self.linker.find_related.call_args.args[1:], ("essays", "orbits"))


class TestFunctional(_Base):
    def test_dream_golden_path_with_image(self):
        img = Path(self.td.name) / "art.png"
        img.write_bytes(b"png")
        self.assertTrue(pj.publish_dream(str(self.dream_file()), str(img)))
        post = (self.root / "content/dreams/2026-05-04.md").read_text()
        self.assertIn('title: "🌙 Glass Tides"', post)
        self.assertIn('description: "A wistful dream about Glass Tides"', post)
        self.assertIn('image: "/images/dreams/2026-05-04.png"', post)
        self.assertIn('tags: ["space", "orbits"]', post)
        self.assertNotIn("# Dream Journal", post)
        self.assertTrue((self.root / "static/images/dreams/2026-05-04.png").exists())
        self.assertEqual(self.git.calls, ["add", "commit", "pull", "push"])

    def test_essay_cli_golden_path(self):
        txt = Path(self.td.name) / "essay.txt"
        txt.write_text("An essay body.")
        with patch.object(sys, "argv", ["x", "essay", "Why Orbits Matter!", "deep_space", str(txt)]):
            pj.main()
        posts = list((self.root / "content/essays").glob("*-why-orbits-matter.md"))
        self.assertEqual(len(posts), 1)
        self.assertIn('description: "A formal essay on Deep Space"', posts[0].read_text())

    def test_cli_errors_exit_1(self):
        for argv in (["x", "essay", "t"], ["x", "bogus"], ["x", "dream"]):
            with patch.object(sys, "argv", argv), self.assertRaises(SystemExit) as cm:
                pj.main()
            self.assertEqual(cm.exception.code, 1)


class TestFrame(unittest.TestCase):
    def test_no_args_prints_usage_and_touches_nothing(self):
        # no --help; with no args main() prints usage and exits 1 before any git/file work
        r = subprocess.run([sys.executable, str(SCRIPT)], capture_output=True, text=True, timeout=30,
                           env={**os.environ, "NOVA_TEST_QUIET": "1"})
        self.assertEqual(r.returncode, 1)
        self.assertIn("Usage: nova_publish_journal.py dream", r.stdout)

    def test_import_never_runs_main(self):
        self.assertIn('if __name__ == "__main__":', SRC)


if __name__ == "__main__":
    unittest.main()
