#!/usr/bin/env python3
"""
nova_dns_sync.py — Nova-DNS: pull UniFi clients, assign STICKY intelligent names,
keep the authoritative map in PG, and emit a dnsmasq hosts file for the `.nova` zone.

So we can stop talking in IP addresses. UniFi is the *feed*; PG (dns_records) is the
authoritative, sticky, overridable source of truth — a device never silently renames
itself, and you can lock/override any name. Static SERVICE aliases (pg-primary.nova,
grafana.nova, …) are re-pointable for failover.

Naming priority: user alias (UniFi `name`) -> reported hostname -> vendor+type ->
mac suffix. Run with --dry-run to preview names without touching PG or dnsmasq.
"""
import argparse
import json
import re
import ssl
import subprocess
import sys
import urllib.request

import psycopg2

DOMAIN = "nova"
DSN = "host=127.0.0.1 dbname=nova_ops user=kochj"
UNIFI = "https://192.168.1.1/proxy/network/api/s/default"
HOSTS_OUT = "/tmp/nova_dns_hosts"   # synced to nuk's dnsmasq addn-hosts

# Static service aliases — re-point these on failover (one record, not a sed sweep).
SERVICE_ALIASES = {
    "pg-primary": "192.168.1.6",
    "grafana":    "192.168.1.2",
    "ollama":     "192.168.1.6",
    "nova-gw":    "192.168.1.6",
    "unas":       "192.168.1.69",
    "nas":        "192.168.1.11",
}

_SSL = ssl.create_default_context()
_SSL.check_hostname = False
_SSL.verify_mode = ssl.CERT_NONE


def api_key():
    return subprocess.run(
        ["security", "find-generic-password", "-a", "nova", "-s", "nova-unifi-api-key", "-w"],
        capture_output=True, text=True, timeout=10).stdout.strip()


def get_clients(key):
    req = urllib.request.Request(f"{UNIFI}/stat/sta", headers={"X-API-Key": key})
    with urllib.request.urlopen(req, timeout=15, context=_SSL) as r:
        return json.loads(r.read()).get("data", [])


def slug(s):
    s = re.sub(r"[^a-z0-9]+", "-", (s or "").strip().lower()).strip("-")
    return re.sub(r"-+", "-", s)


def derive_name(c):
    """Best DNS-safe name for a client, in priority order."""
    for field in ("name", "device_name", "hostname"):
        v = slug(c.get(field))
        if v:
            return v
    vendor = slug(c.get("oui") or c.get("dev_vendor"))
    mac = (c.get("mac") or "").replace(":", "")
    if vendor:
        return f"{vendor}-{mac[-4:]}"
    return f"dev-{mac[-6:]}" if mac else None


def _ensure_schema(conn):
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS dns_records (
                mac text PRIMARY KEY,
                name text NOT NULL,
                ip text,
                source text DEFAULT 'unifi',
                locked boolean DEFAULT false,
                first_seen timestamptz DEFAULT now(),
                updated_at timestamptz DEFAULT now()
            )""")


def build(conn, clients):
    """Return [(fqdn, ip)] and update the sticky PG map (conn=None -> dry-run)."""
    if conn:
        _ensure_schema(conn)
    used_names = {}        # name -> mac, for collision de-dup
    out = []
    for c in clients:
        mac = c.get("mac")
        ip = c.get("ip") or c.get("fixed_ip") or c.get("last_ip")
        if not mac or not ip:
            continue
        existing = None
        if conn:
            with conn.cursor() as cur:
                cur.execute("SELECT name, locked FROM dns_records WHERE mac=%s", (mac,))
                existing = cur.fetchone()
        if existing:                      # sticky: keep the established name
            name = existing[0]
        else:
            name = derive_name(c)
            if not name:
                continue
            # de-dup collisions by appending the mac tail
            if name in used_names and used_names[name] != mac:
                name = f"{name}-{mac.replace(':','')[-4:]}"
        used_names[name] = mac
        if conn:
            with conn.cursor() as cur:
                cur.execute(
                    "INSERT INTO dns_records (mac,name,ip,source) VALUES (%s,%s,%s,'unifi') "
                    "ON CONFLICT (mac) DO UPDATE SET ip=EXCLUDED.ip, updated_at=now()",
                    (mac, name, ip))
        out.append((f"{name}.{DOMAIN}", ip))
    # static service aliases (always emitted, re-pointable)
    for alias, ip in SERVICE_ALIASES.items():
        out.append((f"{alias}.{DOMAIN}", ip))
    return out


def write_hosts(entries, path=HOSTS_OUT):
    lines = [f"{ip} {fqdn}" for fqdn, ip in sorted(entries)]
    with open(path, "w") as f:
        f.write("# generated by nova_dns_sync — do not edit by hand\n")
        f.write("\n".join(lines) + "\n")
    return len(lines)


# DNS nodes that serve the .nova zone (nuk primary + nova-core secondary = HA).
DNS_NODES = ["192.168.1.10", "192.168.1.2"]


def deploy(path=HOSTS_OUT):
    """Push the zone to each DNS node and reload dnsmasq. Best-effort per node."""
    ok = []
    for node in DNS_NODES:
        try:
            subprocess.run(["scp", "-q", "-o", "ConnectTimeout=8", path,
                            f"kochj@{node}:/tmp/nova_dns_hosts"],
                           timeout=25, check=True)
            # /etc so the privilege-dropped dnsmasq user can read it
            subprocess.run(["ssh", "-o", "ConnectTimeout=8", f"kochj@{node}",
                            "sudo cp /tmp/nova_dns_hosts /etc/nova_dns_hosts && "
                            "(sudo systemctl reload dnsmasq 2>/dev/null || sudo systemctl restart dnsmasq)"],
                           timeout=25, check=True)
            ok.append(node)
        except Exception as e:
            print(f"[nova-dns] deploy to {node} failed: {type(e).__name__}", flush=True)
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="preview names, no PG/dnsmasq writes")
    args = ap.parse_args()
    clients = get_clients(api_key())
    conn = None if args.dry_run else psycopg2.connect(DSN)
    if conn:
        conn.autocommit = True
    entries = build(conn, clients)
    if args.dry_run:
        for fqdn, ip in sorted(entries):
            print(f"  {ip:<15} {fqdn}")
        print(f"\n  {len(entries)} records ({len(clients)} clients + {len(SERVICE_ALIASES)} service aliases)")
    else:
        n = write_hosts(entries)
        deployed = deploy()
        print(f"[nova-dns] {n} records, {len(clients)} clients -> served by {len(deployed)}/{len(DNS_NODES)} DNS nodes: {deployed}")
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
